name: Deploy Node.js API to AWS ECS

on:
  workflow_call:
    inputs:
      GITHUB_IMAGE_NAME:
        required: true
        type: string
      GITHUB_IMAGE_TAG:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  aws-ecs-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
          role-session-name: ecs-deployment-${{ inputs.ENVIRONMENT }}

      - name: Pull, tag, and push image to Amazon ECR
        env:
          GITHUB_IMAGE_WITH_TAG: ghcr.io/${{ github.repository }}/${{ inputs.GITHUB_IMAGE_NAME }}:${{ inputs.GITHUB_IMAGE_TAG }}
        run: |
          docker pull ${GITHUB_IMAGE_WITH_TAG}
